CREATE DATABASE VENTAS
GO
USE VENTAS
GO

CREATE TABLE CLIENTE(
ID_CLI INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(50)NOT NULL
)
GO

CREATE TABLE PRODUCTO(
ID_PRO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
PRECIO_U DECIMAL(16,2)NOT NULL,
COSTO DECIMAL(16,0)NOT NULL
)
GO

CREATE TABLE VENTA(
ID_VENTA BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
FECHA DATETIME NOT NULL,
ID_CLIENTE INT NOT NULL,
TOTAL DECIMAL(16,2)NULL
CONSTRAINT IDCLIENTE
FOREIGN KEY (ID_CLIENTE)
REFERENCES CLIENTE(ID_CLI)
)
GO

CREATE TABLE DETALLE_VENTA(
IDD_VENTA BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
ID_VENTA BIGINT NOT NULL,
ID_PROD INT NOT NULL,
CANTIDAD INT NOT NULL,
PRECIO_UNI DECIMAL (16,2) NOT NULL,
IMPORTE DECIMAL (16,2) NOT NULL
CONSTRAINT IDVENTAS
FOREIGN KEY (ID_VENTA)
REFERENCES VENTA(ID_VENTA),
CONSTRAINT IDPRODUCTO
FOREIGN KEY (ID_PROD)
REFERENCES PRODUCTO(ID_PRO)
)
GO

CREATE TABLE USUARIOS(
IDUSR BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
USERNAME VARCHAR(20)NOT NULL,
EMAIL NVARCHAR(30) UNIQUE,
PASSWORD VARBINARY(8000)
)
GO

CREATE PROC RegistrarUsuario
	@USERNAME VARCHAR(20),
	@EMAIL VARCHAR(30),
	@PASSWORD NVARCHAR(30)
AS
BEGIN
INSERT INTO USUARIOS VALUES
(
	@USERNAME,
	@EMAIL,
	ENCRYPTBYPASSPHRASE('PASSWORD',@PASSWORD)
)
END
GO

EXEC RegistrarUsuario
'Rengoku', 'rengoku@gmail.com','A$hen0n3'

INSERT INTO CLIENTE VALUES
('DEKU'),
('TOMIOKA'),
('ROKU'),
('ONODERA')
GO

INSERT INTO PRODUCTO VALUES
('Senbei',10.50,15.00),
('Kaki no Tane',07.20,12.00),
('Arare',17.80,24.00),
('Amaibo',08.00,15.00),
('Anpan',12.48,17.25),
('Tokyo Banana',37.82,45.80),
('Pretz',48.50,60.20),
('Pocky',53.73,73.69)
GO

INSERT INTO VENTA VALUES
('2021-11-17',1,73.69),
('2021-11-16',4,60.20),
('2021-11-17',2,12.00),
('2021-11-17',3,24.00)
GO

INSERT INTO DETALLE_VENTA VALUES
(1,8,1,73.69,73.69)
GO

SELECT*FROM DETALLE_VENTA
SELECT*FROM VENTA
SELECT*FROM CLIENTE
SELECT*FROM PRODUCTO

SELECT*FROM USUARIOS
SELECT CONVERT(nvarchar(MAX), DECRYPTBYPASSPHRASE('PASSWORD',USUARIOS.PASSWORD)) FROM USUARIOS
SELECT username , CONVERT(nvarchar(MAX), DECRYPTBYPASSPHRASE('PASSWORD',USUARIOS.PASSWORD))as password FROM USUARIOS
